### ISSUE TITLE
Add expiry to the public key cache

### ISSUE THREAD

**Issue by frjtrifork** [justinlettau/azure-ad-verify-token#2]
## Describe the Feature

Currently the public key cache value is set when the value is fetched and subsequent calls that need the public keys will get the cached version. Unless I missed something in the code, the cached value does not expire.
For short running applications this is not a problem. 
But for long running applications like a rest-api this could be a problem once the keys in Azure are rotated and the application has not restarted.

## Suggested Solution

Change the current Map<string, string> to a Map<string, object> where the object contains both an expiry value which should be a timestamp as well as the string. 

When the value is initially populated set the expiry value to a timestamp in the future - e.g. `expiry = new Date().getTime() + cacheLifeTimeMs` where cacheLifeTimeMs is  the allowed life time of the cached value in ms. The cacheLifeTimeMs could be a configurable value - and maybe default to a 1 hour life time if not configured.

On subsequent get calls to the cache, the cached value is ok if `expiry > new Date().getTime()` - otherwise it should be deleted, and a new fresh value should be fetched and cached.

## Other Information

n/a
I will be happy to make a PR if such are accepted?

**Comment by justinlettau** [comment]
@frjtrifork Yes! PR would be welcomed!

**Comment by justinlettau** [comment]
@frjtrifork Just pushed this 🎉 Will be in next release! Thanks
