### ISSUE TITLE
Error JsonWebTokenError: invalid signature

### ISSUE THREAD

**Issue by voyager163** [justinlettau/azure-ad-verify-token#36]
I am facing issue in verifying my oauth ID token. 

When i use the id token obtain from the aad_oauth flutter , i am facing a error "JWTVerification:: Error JsonWebTokenError: invalid signature". Do you know what is the id token failed the check?

When i use jwt.ms, everything look likes it is in order.

**Comment by justinlettau** [comment]
Based on the error you provided, it looks like the error is actually coming from `jsonwebtoken` ([here](https://github.com/auth0/node-jsonwebtoken/blob/74d5719bd03993fcf71e3b176621f133eb6138c0/verify.js#L133)). I would recommend trying verify our token via `jsonwebtoken` (via [verify](https://github.com/auth0/node-jsonwebtoken/tree/74d5719bd03993fcf71e3b176621f133eb6138c0#jwtverifytoken-secretorpublickey-options-callback)) directly to see the result.
