### ISSUE TITLE
Cannot read property 'header' of null

### ISSUE THREAD

**Issue by thgh** [justinlettau/azure-ad-verify-token#4]
Invalid tokens might be null:
https://github.com/auth0/node-jsonwebtoken/blob/5f10bf9957a2541828501cfecab0310908b2f62f/decode.js#L6

That is why this code throws `Cannot read property 'header' of null `
https://github.com/justinlettau/azure-ad-verify-token/blob/b0fbe8c966d549a90ff12f9a3b31595aad547d58/src/verify.ts#L54-L55

Instead, it would make sense to throw an `'invalid token'` error like here:
https://github.com/auth0/node-jsonwebtoken/blob/5f10bf9957a2541828501cfecab0310908b2f62f/verify.js#L75

**Comment by justinlettau** [comment]
Pushed; Will be updated in next release 🎉
