### ISSUE TITLE
dynamic import() does not work

### ISSUE THREAD

**Issue by slavonicsniper** [justinlettau/azure-ad-verify-token#47]
## Describe the Issue

As I currently cannot import the package in our nx based project because of `Error [ERR_REQUIRE_ESM]: require() of ES Module not supported.` I wanted to use a dynamic import to load the package but it looks like it does not work neither.
const { verify } = import('azure-ad-verify-token');
console.log(verify) -> { default: {} }

Todo

## Expected behavior

dynamic import loads the package correctly

Todo

## Steps to Reproduce

npm install azure-ad-verify-token
const { verify } = import('azure-ad-verify-token');
verify() -> verify is not a function

n/a

## Other Information

n/a

**Comment by justinlettau** [comment]
Dynamic imports are asynchronous ([see here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import#return_value)). So you'll need to use `.then()` or `await` like this:

```ts
async function main() {
  const { verify } = await import('azure-ad-verify-token');

  try {
    await verify(myToken, {
      jwksUri: process.env.JWKS_URI,
      issuer: process.env.ISSUER,
      audience: process.env.AUDIENCE,
    });
  } catch (error) {
    console.log(error);
  }
}
```

If you have issues with that, feel free to reopen, thanks.
