### ISSUE TITLE
Import failure

### ISSUE THREAD

**Issue by koshonson** [justinlettau/azure-ad-verify-token#54]
## Import of verify function fails

I'm facing a similar problem that was described in [issue#45](https://github.com/justinlettau/azure-ad-verify-token/issues/45). In my `nestjs` project, I can import `verify` function from the package without any typescript warnings, but the compilation fails with following message:

```
Error [ERR_REQUIRE_ESM]: require() of ES Module ...\node_modules\azure-ad-verify-token\dist\index.js from ...\my-project-file.js not supported.
Instead change the require of index.js in ...\my-project-file.js to a dynamic import() which is available in all CommonJS modules.
```

Using a dynamic import would be a bit annoying as I cannot use top-level await due to standard `nestjs` project configuration, which I'm not allowed to alter easily. 

When I try dynamic import in a function (with regards to the advice from [issue#47](https://github.com/justinlettau/azure-ad-verify-token/issues/47)), the code compiles. However, strange enough, when the function with dynamic import runs, the app crashes with the very same error message - including the _"change to a dynamic import()"_ hint.

## Expected behavior

I can import `verify` function from the package and use it without any compilation errors or application crashes.

## Steps to Reproduce

I'm trying to use the package (version `3.0.0`, but downgrading to `2.0.1` doesn't help) in a standard `nestjs` project generated from Nest CLI. 

From project's `package.json`:

```json
...
"dependencies": {
    "@nestjs/common": "^9.0.0",
    "@nestjs/config": "^2.2.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/mongoose": "^9.2.1",
    "@nestjs/platform-express": "^9.0.0",
    "azure-ad-verify-token": "^3.0.0",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.14.0",
    "cookie-session": "^2.0.0",
    "mongoose": "^6.7.3",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0"
  },
"devDependencies": {
    ...
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "4.1.0",
    "typescript": "^4.7.4"
  }
...
```

Here's my `tsconfig.json`:

```json
"compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "es2017",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true,
    "skipLibCheck": true,
    "strictNullChecks": false,
    "noImplicitAny": false,
    "strictBindCallApply": false,
    "forceConsistentCasingInFileNames": false,
    "noFallthroughCasesInSwitch": false
  }
```

The code looks like so:
```ts
import {verify, VerifyOptions} from 'azure-ad-verify-token';
// other imports

const options: VerifyOptions = {
  jwksUri: 'https://my-jwksUri',
  issuer: 'https://my-issuer',
  audience: 'my-audience'
};

@Injectable()
export class CurrentUserMiddleware implements NestMiddleware {
  constructor(private usersService: UsersService) {}

  async use(req: Request, res: Response, next: NextFunction) {
    const token = req.headers['authorization'];

    try {
      const resolved = await verify(token, options);
      console.log(resolved);
    } catch (err) {
      console.log('azure-ad-verify-token/verify FAILED');
      console.log(err);
    }

    // some more code
  }
}
```

**Comment by justinlettau** [comment]
This package is an ESM now. This info [here](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c) should be what you need. Hope that helps!
