### ISSUE TITLE
dynamic import() error

### ISSUE THREAD

**Issue by sshehab1** [justinlettau/azure-ad-verify-token#57]
Hello,
I am getting this error:
`Worker was unable to load function etdoUploadFunc: 'require() of ES Module C:\projects\node_modules\azure-ad-verify-token\dist\index.js from C:\projects\api\dist\api\authMiddleware.js not supported.
Instead change the require of index.js in C:\projects\api\dist\api\authMiddleware.js to a dynamic import() which is available in all CommonJS modules.'`

but I am using `import { verify, VerifyOptions } from 'azure-ad-verify-token';`
version:  `"azure-ad-verify-token": "^3.0.1"`

I also tried   `const { verify } = await import('azure-ad-verify-token');` but I am getting this error `Result: Failure
Exception: require() of ES Module`

**Comment by vitjaz** [comment]
Same error

**Comment by justinlettau** [comment]
@sshehab1 You might find some [help here](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c) for how to enable ESM packages in your project. If you using TypeScript, and want to use `await import()`, try adding `"moduleResolution": "Node16",` to your tsconfig compiler options. 

@vitjaz Adding `"moduleResolution": "Node16",` + using `await import()` seems to work for NestJS projects too.

**Comment by benjaminknox** [comment]
I struggled with this all day today, adding `"moduleResolution": "Node16",` + using `await import()` works really well.
